services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql
    networks:
      - auction-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongodb:
    image: mongo
    # For Harbor: harbor.example.com/auction-project/mongodb:latest
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mongopw
    ports:
      - "27017:27017"
    volumes:
      - /var/lib/mongodb/data
    networks:
      - auction-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  auction-svc:
    image: auction-svc:latest
    # For Harbor: harbor.example.com/auction-project/auction-svc:1.0.0
    container_name: auction-svc
    build:
      context: .
      dockerfile: src/AuctionService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:7001
      - ConnectionStrings__DefaultConnection=Server=postgres;Port=5432;Database=auctiondb;User Id=postgres;Password=postgrespw;
    ports:
      - "7001:7001"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - auction-network

  search-svc:
    image: search-svc:latest
    # For Harbor: harbor.example.com/auction-project/search-svc:1.0.0
    container_name: search-svc
    build:
      context: .
      dockerfile: src/SearchService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:7002
      - ConnectionStrings__MongoDbConnection=mongodb://root:mongopw@mongodb
      - AuctionServiceUrl=http://auction-svc:7001/
    ports:
      - "7002:7002"
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - auction-network

networks:
  auction-network:
    driver: bridge

volumes:
  pgdata:
